version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootPassword
    networks:
      - app-network
  backend:
    build:
      context: ./
    container_name: backend
    # environment:
    #   - PORT=3000
    #   - MONGO_URI=mongodb://mongodb:27017/feedAppDB
    #   - FRONTEND=http://frontend:5173/
    #   - JWT_SECRET=secretKey
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network
  frontend:
    build:
      context: ./pollApp
    container_name: frontend
    volumes:
      - ./pollApp:/app
    # environment:
    #   - BACKEND=http://backend:3000/
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
