version: "3.8"
services:
  postgres:
    image: postgres:14
    container_name: postgres-feedapp
    environment:
      POSTGRES_USER: feed-app-user
      POSTGRES_PASSWORD: feedapp123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
